# Generated by Django 3.0.5 on 2021-02-02 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='userMedia', validators=[users.validators.validate_file_size])),
                ('is_admin', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('store_json', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
