# Generated by Django 3.0.5 on 2021-02-02 08:54

from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='eventsMedia', validators=[events.validators.validate_file_size])),
                ('is_pinned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-startTime'],
            },
        ),
    ]
