# Generated by Django 3.0.5 on 2021-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
